version: '3.7'
#
services:
  irissvc:
    build:
       context: .
       dockerfile: Dockerfile
    container_name: faqdemo
    restart: always
    
    ports:
    # superserver default port 
    - "51775:1972"
    # webserver/management portal port
    - "52775:52773"
    
    environment:
    - TZ=JST-9